version: 2
updates:
  - package-ecosystem: pip
    directory: /
    groups:
      py-minor-and-patch:
        update-types:
          - minor
          - patch
    schedule:
      interval: daily
    cooldown:
      default-days: 5
      semver-major-days: 30
      semver-minor-days: 7
      semver-patch-days: 3
  - package-ecosystem: npm
    directory: /
    groups:
      npm-minor-and-patch:
        update-types:
          - minor
          - patch
    schedule:
      interval: daily
    cooldown:
      default-days: 5
      semver-major-days: 30
      semver-minor-days: 7
      semver-patch-days: 3
  - package-ecosystem: github-actions # zizmor: ignore[dependabot-cooldown]
    directory: /
    groups:
      gha-minor-and-patch:
        update-types:
          - minor
          - patch
    schedule:
      interval: daily
